spring:
    application:
        name: walleye-backend
    profiles:
        active: [dev,secret]

    mail:
        host: smtp.gmail.com #pro.turbo-smtp.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                debug: true


    datasource:
        url: jdbc:postgresql://db.qqbzkaepnjhldcmxlhxj.supabase.co:5432/postgres
        username: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect

email:
  remetente: caioguih03@gmail.com
  destinatarios: 
    - omemoriamaster@gmail.com
    - guga.f.martins09@gmail.com
    - rodrigoabade26@gmail.com